# -*- coding: utf-8 -*-
"""dueling_dqn_sb3_noVn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yLBCJhJWmJZOeypVJxkgJZDt-6oAfDpK
"""

# !rm -rf /content/Tetris_RL
# !rm -rf /content/drive/MyDrive/tetris_dueling_sb3_logs_V1
# !rm /content/tetris_register.py
# !rm /content/Tetris_RL.zip

from google.colab import drive
drive.mount('/content/drive')

!pip install gymnasium stable-baselines3[extra] pygame

import sys
sys.path.append("/content/drive/MyDrive/Tetris_RL")
# add project to python path, allows python to find the files while importing

from tetris.tetris_env import TetrisGymEnv
from tetris.tetris_engine import TetrisEngine

# sample=TetrisGymEnv(observation_type="board_and_heuristics", death_penalty=0)
# print(sample.death_penalty)
# print(sample.max_steps)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile tetris_register.py
# from gymnasium.envs.registration import register
# 
# register(
#     id="Tetris-v0",
#     entry_point="tetris.tetris_env:TetrisGymEnv",
# )

import tetris_register

import os
import glob
from stable_baselines3 import DQN
from stable_baselines3.common.vec_env import DummyVecEnv, VecNormalize
from stable_baselines3.common.monitor import Monitor
from stable_baselines3.common.callbacks import CheckpointCallback, EvalCallback
import gymnasium as gym

import torch
import torch.nn as nn
from stable_baselines3.dqn.policies import DQNPolicy, QNetwork, MultiInputPolicy

class DuelingQNetwork(QNetwork):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Override the q_net created by the parent class
        # with a dueling architecture
        net_arch = kwargs.get("net_arch", [256, 256])
        if net_arch is None or len(net_arch) == 0:
            net_arch = [256, 256]

        # Value stream
        self.value_net = nn.Sequential(
            nn.Linear(self.features_dim, net_arch[0]),
            nn.ReLU(),
            nn.Linear(net_arch[0], net_arch[1]),
            nn.ReLU(),
            nn.Linear(net_arch[1], 1)
        )

        # Advantage stream
        self.advantage_net = nn.Sequential(
            nn.Linear(self.features_dim, net_arch[0]),
            nn.ReLU(),
            nn.Linear(net_arch[0], net_arch[1]),
            nn.ReLU(),
            nn.Linear(net_arch[1], self.action_space.n)
        )

    def forward(self, obs: torch.Tensor) -> torch.Tensor:
        features = self.extract_features(obs, self.features_extractor)
        value = self.value_net(features)
        advantages = self.advantage_net(features)
        # Combine value and advantage: Q(s,a) = V(s) + A(s,a) - mean(A(s,a))
        q_values = value + (advantages - advantages.mean(dim=1, keepdim=True))
        return q_values

class DuelingDQNPolicy(MultiInputPolicy):
    def make_q_net(self) -> DuelingQNetwork:
        net_args = self._update_features_extractor(self.net_args, features_extractor=None)
        return DuelingQNetwork(**net_args).to(self.device)

# obj=TetrisGymEnv(observation_type="board_and_heuristics")
# print(obj.lines_cleared_reward, obj.step_penalty)

# Create environment factory so DummyVecEnv can make it
def make_env():
    def _init():
        env = gym.make("Tetris-v0", observation_type="board_and_heuristics", death_penalty=-10)
        # force the correct observation type
        env = Monitor(env)
        # print(f"step penalty = {env.step_penalty}")
        return env
    return _init

import re
import os
import glob
import numpy as np
import torch as th
import torch.nn as nn
from stable_baselines3 import DQN
from stable_baselines3.common.vec_env import DummyVecEnv, VecNormalize
from stable_baselines3.common.monitor import Monitor
from stable_baselines3.common.callbacks import CheckpointCallback, EvalCallback, BaseCallback
from stable_baselines3.common.buffers import DictReplayBuffer

# --- PER Implementation ---
class PrioritizedDictReplayBuffer(DictReplayBuffer):
    def __init__(self, buffer_size, observation_space, action_space, device="auto", n_envs=1, alpha=0.6):
        super(PrioritizedDictReplayBuffer, self).__init__(buffer_size, observation_space, action_space, device, n_envs)
        self.alpha = alpha
        self.priorities = np.zeros((self.buffer_size,), dtype=np.float32)
        self.max_priority = 1.0

    def add(self, obs, next_obs, action, reward, done, infos):
        super().add(obs, next_obs, action, reward, done, infos)
        self.priorities[self.pos - 1] = self.max_priority

    def sample(self, batch_size, env=None):
        if self.full:
            priorities = self.priorities
        else:
            priorities = self.priorities[:self.pos]

        probs = priorities ** self.alpha
        probs /= probs.sum()

        indices = np.random.choice(len(probs), batch_size, p=probs)
        samples = self._get_samples(indices, env=env)
        samples = samples._replace(weights=th.ones(batch_size).to(self.device))
        return samples

    def update_priorities(self, indices, priorities):
        for idx, priority in zip(indices, priorities):
            self.priorities[idx] = priority
        self.max_priority = max(self.max_priority, priorities.max())

# --- Custom Callbacks ---
class SaveReplayBufferCallback(BaseCallback):
    def __init__(self, save_path: str, save_freq: int, verbose=1):
        super().__init__(verbose)
        self.save_path = save_path
        self.save_freq = save_freq
    def _on_step(self) -> bool:
        if self.n_calls % self.save_freq == 0:
            path = os.path.join(self.save_path, "replay_buffer.pkl")
            self.model.save_replay_buffer(path)
        return True

class SaveVecNormalizeCallback(BaseCallback):
    def __init__(self, save_path: str, save_freq: int = 0, verbose=1):
        super().__init__(verbose)
        self.save_path = save_path
        self.save_freq = save_freq
    def _init_callback(self) -> None:
        if self.save_path is not None: os.makedirs(self.save_path, exist_ok=True)
    def _on_step(self) -> bool:
        if self.save_freq > 0 and self.n_calls % self.save_freq == 0:
            path = os.path.join(self.save_path, "vecnormalize.pkl")
            self.training_env.save(path)
        return True

# GPU CHECK
device = "cuda" if th.cuda.is_available() else "cpu"
print(f"Using device: {device}")

# PARAMETERS
ENV_ID = "Tetris-v0"
TIMESTEPS = 10_000_000
EVAL_FREQ = 100_000
CHECKPOINT_FREQ = 100_000
LOG_DIR = "/content/drive/MyDrive/tetris_dueling_sb3_logs_V5"

checkpoint_dir = os.path.join(LOG_DIR, "checkpoints")
checkpoint_files = glob.glob(os.path.join(checkpoint_dir, "tetris_dqn_*.zip"))

vec_env = DummyVecEnv([make_env()])
vec_env = VecNormalize(vec_env, norm_obs=False, norm_reward=True)
eval_env = DummyVecEnv([make_env()])
eval_env = VecNormalize(eval_env, norm_obs=False, norm_reward=True)
eval_env.training = False
eval_env.norm_reward = False

if checkpoint_files:
    latest_checkpoint = max(checkpoint_files, key=os.path.getmtime)
    match = re.search(r'tetris_dqn_(\d+)_steps', os.path.basename(latest_checkpoint))
    remaining_steps = TIMESTEPS - int(match.group(1)) if match else TIMESTEPS
    model = DQN.load(latest_checkpoint, env=vec_env, device=device)

    replay_path = os.path.join(checkpoint_dir, "replay_buffer.pkl")
    if os.path.exists(replay_path): model.load_replay_buffer(replay_path)

    vecnorm_path = os.path.join(checkpoint_dir, "vecnormalize.pkl")
    if os.path.exists(vecnorm_path):
        vec_env = VecNormalize.load(vecnorm_path, vec_env)
        eval_env = VecNormalize.load(vecnorm_path, eval_env)
        eval_env.training = False
        eval_env.norm_reward = False
    model.set_env(vec_env)
else:
    remaining_steps = TIMESTEPS
    from stable_baselines3.common.torch_layers import BaseFeaturesExtractor

    class TetrisCombinedExtractor(BaseFeaturesExtractor):
        def __init__(self, observation_space, features_dim: int = 512):
            super().__init__(observation_space, features_dim)
            board_shape = observation_space['board'].shape
            feature_shape = observation_space['features'].shape
            self.cnn = nn.Sequential(
                nn.Conv2d(board_shape[0], 32, 3, padding=1), nn.ReLU(),
                nn.Conv2d(32, 64, 3, padding=1), nn.ReLU(),
                nn.Flatten()
            )
            with th.no_grad():
                conv_out = self.cnn(th.zeros(1, *board_shape)).shape[1]
            self.mlpf = nn.Sequential(nn.Linear(feature_shape[0], 64), nn.ReLU())
            self.final_mlp = nn.Sequential(nn.Linear(conv_out + 64, 512), nn.ReLU(), nn.Linear(512, features_dim), nn.ReLU())
        def forward(self, observations):
            return self.final_mlp(th.cat([self.cnn(observations['board']), self.mlpf(observations['features'])], dim=1))

    model = DQN(
        policy=DuelingDQNPolicy,
        env=vec_env,
        learning_rate=1e-4,
        buffer_size=200_000,
        replay_buffer_class=PrioritizedDictReplayBuffer,
        replay_buffer_kwargs=dict(alpha=0.6),
        learning_starts=10_000,
        batch_size=128,
        gamma=0.99,
        train_freq=(4, "step"),
        target_update_interval=1000,
        exploration_fraction=0.15,
        exploration_final_eps=0.05,
        policy_kwargs=dict(features_extractor_class=TetrisCombinedExtractor, features_extractor_kwargs=dict(features_dim=512)),
        verbose=1,
        tensorboard_log=LOG_DIR,
        device=device
    )

checkpoint_cb = CheckpointCallback(save_freq=CHECKPOINT_FREQ, save_path=checkpoint_dir, name_prefix="tetris_dqn")
save_replay_cb = SaveReplayBufferCallback(save_path=checkpoint_dir, save_freq=CHECKPOINT_FREQ)
save_vec_cb = SaveVecNormalizeCallback(save_path=checkpoint_dir, save_freq=CHECKPOINT_FREQ)
eval_cb = EvalCallback(eval_env, best_model_save_path=os.path.join(LOG_DIR, "best_model"), eval_freq=EVAL_FREQ, n_eval_episodes=8)

model.learn(total_timesteps=remaining_steps, callback=[checkpoint_cb, eval_cb, save_replay_cb, save_vec_cb], reset_num_timesteps=False)
model.save(os.path.join(LOG_DIR, "tetris_dueling_dqn_final"))
vec_env.save(os.path.join(LOG_DIR, "vecnormalize.pkl"))

# import os

# # Let's verify the directory structure and see what files are actually there
# print(f"Checking LOG_DIR: {LOG_DIR}")
# if os.path.exists(LOG_DIR):
#     print("Contents of LOG_DIR:", os.listdir(LOG_DIR))

#     checkpoint_path = os.path.join(LOG_DIR, "checkpoints")
#     if os.path.exists(checkpoint_path):
#         print(f"\nContents of {checkpoint_path}:")
#         files = os.listdir(checkpoint_path)
#         for f in files:
#             print(f" - {f}")
#     else:
#         print(f"\nSubdirectory 'checkpoints' does not exist in {LOG_DIR}")
# else:
#     print(f"Error: The path {LOG_DIR} does not exist. Please check if your Drive is mounted correctly or if the path is correct.")

import os
from stable_baselines3 import DQN
from stable_baselines3.common.vec_env import DummyVecEnv, VecNormalize

# 1. Define the base path to your Drive folder
# Adjust 'Tetris_RL' if your logs are in a specific subfolder inside MyDrive
log_path = "/content/drive/MyDrive/tetris_dueling_sb3_logs_V5/"

# 2. Check if the file actually exists (Good for debugging)
vec_norm_path = os.path.join(log_path, "best_model/vecnormalize.pkl")
model_path = os.path.join(log_path, "best_model/best_model.zip") # .zip is often implicit in SB3, but good to be aware of

if not os.path.exists(vec_norm_path):
    print(f"Error: Could not find file at {vec_norm_path}")
    print("Available files in folder:", os.listdir(log_path))
else:
    # 3. Load the environment and model using the corrected paths

    # base env (assuming make_env is defined elsewhere in your code)
    dummy = DummyVecEnv([make_env()])

    # load normalization wrapper
    vec_env = VecNormalize.load(vec_norm_path, dummy)
    vec_env.training = False
    vec_env.norm_reward = False

    # load the trained model
    # Note: DQN.load handles the .zip extension automatically if omitted,
    # but the directory path must be correct.
    model = DQN.load(model_path, env=vec_env)

    print("Model loaded successfully!")

obs = vec_env.reset()
done = False
total_reward = 0
total_lines_cleared = 0
action_no=1

while not done:
    action, _ = model.predict(obs, deterministic=True)
    print(f"action {action_no}:", action)
    action_no+=1
    obs, reward, done, info = vec_env.step(action)
    print("reward", reward)
    total_reward += reward
    total_lines_cleared += info[0]['lines_cleared']

    vec_env.envs[0].render()

print("Episode finished. Total reward:", total_reward)
print("Lines cleared:", total_lines_cleared)